name: open-standard-models
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyterlab
  - nomkl
  - numpy
  - pip
  - pandas
  - pyarrow
  - python-graphviz
  - seaborn
  - scikit-learn
  - matplotlib
  - h5py
  - requests
  - pytables
  - pip:
    - SKompiler[full]
    - nyoka

